// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMGFknXPz8l2TXdqrO6phzrZxdEt3ehFA',
    appId: '1:379656218383:web:9312f0ae55226ea7e8407a',
    messagingSenderId: '379656218383',
    projectId: 'chatap-68fc4',
    authDomain: 'chatap-68fc4.firebaseapp.com',
    storageBucket: 'chatap-68fc4.appspot.com',
    measurementId: 'G-G1WVKL128G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxiHe-HlGCakco-Zglv_plCPVdS2vndP8',
    appId: '1:379656218383:android:06a414a4af0f7f7de8407a',
    messagingSenderId: '379656218383',
    projectId: 'chatap-68fc4',
    storageBucket: 'chatap-68fc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7hnpbCJN9FLhA2DmQWZJ4yAIQRlSbmgU',
    appId: '1:379656218383:ios:d1c363bef01612a5e8407a',
    messagingSenderId: '379656218383',
    projectId: 'chatap-68fc4',
    storageBucket: 'chatap-68fc4.appspot.com',
    iosBundleId: 'com.example.chatin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMGFknXPz8l2TXdqrO6phzrZxdEt3ehFA',
    appId: '1:379656218383:web:c39a6cd002ec281ee8407a',
    messagingSenderId: '379656218383',
    projectId: 'chatap-68fc4',
    authDomain: 'chatap-68fc4.firebaseapp.com',
    storageBucket: 'chatap-68fc4.appspot.com',
    measurementId: 'G-CR4591MXNR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7hnpbCJN9FLhA2DmQWZJ4yAIQRlSbmgU',
    appId: '1:379656218383:ios:d1c363bef01612a5e8407a',
    messagingSenderId: '379656218383',
    projectId: 'chatap-68fc4',
    storageBucket: 'chatap-68fc4.appspot.com',
    iosBundleId: 'com.example.chatin',
  );
}
